use crate::prelude::*;

pub const MIN_YEAR: usize = 1900;
pub const MAX_YEAR: usize = 2025;

pub const BRAND_TOKENS: [(&str, &[&str]); 300] = [
    ("A. Favre & Fils", &["a.", "favre", "fils"]),
    ("Adidas Originals", &["adidas", "originals"]),
    ("Arnold & Son", &["arnold", "son"]),
    ("A. Lange & Söhne", &["a.", "lange", "sohne"]),
    ("Accurist", &["accurist"]),
    ("Abraham-Louis Breguet", &["abraham-louis", "breguet"]),
    ("Adriatica", &["adriatica"]),
    ("ADINA Watches", &["adina", "watches"]),
    ("Anne Klein", &["anne", "klein"]),
    ("A.L.B Atelier Le Brézéguet", &["a.l.b", "atelier", "le", "brezeguet"]),
    ("Amanda Walker", &["amanda", "walker"]),
    ("Alba", &["alba"]),
    ("Alexandre Christie", &["alexandre", "christie"]),
    ("Andreas Osten", &["andreas", "osten"]),
    ("Andersen Geneve", &["andersen", "geneve"]),
    ("Ansonia Clock Company", &["ansonia", "clock", "company"]),
    ("American Waltham Watch Company", &["american", "waltham", "watch", "company"]),
    ("Armani Exchange", &["armani", "exchange"]),
    ("Apple", &["apple"]),
    ("anOrdain", &["anordain"]),
    ("August Berg x Morris & Co", &["august", "berg", "x", "morris", "co"]),
    ("AKRIVIA", &["akrivia"]),
    ("Akrone", &["akrone"]),
    ("AVI-8", &["avi-8"]),
    ("Alexander Shorokhoff", &["alexander", "shorokhoff"]),
    ("Alpina", &["alpina"]),
    ("Aragon", &["aragon"]),
    ("Andreas Strehler", &["andreas", "strehler"]),
    ("Angelus", &["angelus"]),
    ("Anonimo", &["anonimo"]),
    ("Antoine Preziuso", &["antoine", "preziuso"]),
    ("Armand Nicolet", &["armand", "nicolet"]),
    ("Armin Strom", &["armin", "strom"]),
    ("Armitron", &["armitron"]),
    ("Ateliers de Monaco", &["ateliers", "de", "monaco"]),
    ("Audemars Piguet", &["audemars", "piguet"]),
    ("Auguste Reymond", &["auguste", "reymond"]),
    ("Azimuth", &["azimuth"]),
    ("Aquastar", &["aquastar"]),
    ("Backes & Strauss", &["backes", "strauss"]),
    ("Ball Watch", &["ball", "watch"]),
    ("Bausele", &["bausele"]),
    ("Bruno Sohnle", &["bruno", "sohnle"]),
    ("B-UHR", &["b-uhr"]),
    ("Baume & Mercier", &["baume", "mercier"]),
    ("Bell & Ross", &["bell", "ross"]),
    ("Bovet Fleurier", &["bovet", "fleurier"]),
    ("Bedat & Co", &["bedat", "co"]),
    ("Benrus", &["benrus"]),
    ("Blancpain", &["blancpain"]),
    ("Blumarine", &["blumarine"]),
    ("Ben Sherman", &["ben", "sherman"]),
    ("Bulova", &["bulova"]),
    ("Breil", &["breil"]),
    ("Bomberg", &["bomberg"]),
    ("Bovet", &["bovet"]),
    ("Breguet", &["breguet"]),
    ("Breitling", &["breitling"]),
    ("Brellum", &["brellum"]),
    ("Bremont", &["bremont"]),
    ("Bvlgari", &["bvlgari"]),
    ("Burberry", &["burberry"]),
    ("Buccellati", &["buccellati"]),
    ("Carl F. Bucherer", &["carl", "f.", "bucherer"]),
    ("Carl Suchy & Söhne", &["carl", "suchy", "sohne"]),
    ("Cartier", &["cartier"]),
    ("Calvin Klein", &["calvin", "klein"]),
    ("Catorex", &["catorex"]),
    ("Carlo Ferrara", &["carlo", "ferrara"]),
    ("Century", &["century"]),
    ("Certina", &["certina"]),
    ("Cecil Purnell", &["cecil", "purnell"]),
    ("Christian Jacques", &["christian", "jacques"]),
    ("Christopher Ward", &["christopher", "ward"]),
    ("Chanel", &["chanel"]),
    ("Charriol", &["charriol"]),
    ("Chopard", &["chopard"]),
    ("Citizen", &["citizen"]),
    ("Coach", &["coach"]),
    ("Christophe Claret", &["christophe", "claret"]),
    ("Chronoswiss", &["chronoswiss"]),
    ("Charles Jourdan", &["charles", "jourdan"]),
    ("Calypso", &["calypso"]),
    ("Claude Meylan", &["claude", "meylan"]),
    ("Charlotte Raffaelli", &["charlotte", "raffaelli"]),
    ("Cluse", &["cluse"]),
    ("Code41", &["code41"]),
    ("Corum", &["corum"]),
    ("CT Scuderia", &["ct", "scuderia"]),
    ("Cuervo y Sobrinos", &["cuervo", "y", "sobrinos"]),
    ("Cvstos", &["cvstos"]),
    ("Cyrus", &["cyrus"]),
    ("Czapek", &["czapek"]),
    ("Daniel Wellington", &["daniel", "wellington"]),
    ("De Bethune", &["de", "bethune"]),
    ("Dewitt", &["dewitt"]),
    ("DKNY", &["dkny"]),
    ("Dakota Watch Company", &["dakota", "watch", "company"]),
    ("Dior", &["dior"]),
    ("Damasko", &["damasko"]),
    ("D. Dornblüth & Sohn", &["d.", "dornbluth", "sohn"]),
    ("Damiani", &["damiani"]),
    ("Dan henry", &["dan", "henry"]),
    ("D1 Milano", &["d1", "milano"]),
    ("Depth Charge", &["depth", "charge"]),
    ("Delbana", &["delbana"]),
    ("Diesel", &["diesel"]),
    ("Delma", &["delma"]),
    ("Dietrich", &["dietrich"]),
    ("Dreffa", &["dreffa"]),
    ("Dubey Schaldenbrand", &["dubey", "schaldenbrand"]),
    ("Doxa", &["doxa"]),
    ("Ebel", &["ebel"]),
    ("Eberhard & Co", &["eberhard", "co"]),
    ("Edox", &["edox"]),
    ("EHF Horlogere", &["ehf", "horlogere"]),
    ("EPOS", &["epos"]),
    ("Ernest Borel", &["ernest", "borel"]),
    ("Emile Chouriet", &["emile", "chouriet"]),
    ("Eterna", &["eterna"]),
    ("Elliot Brown", &["elliot", "brown"]),
    ("Epoch Stockholm", &["epoch", "stockholm"]),
    ("EverSwiss", &["everswiss"]),
    ("F. P. Journe", &["f.", "p.", "journe"]),
    ("Fabergé", &["faberge"]),
    ("Favre Leuba", &["favre", "leuba"]),
    ("Ferdinand Berthoud", &["ferdinand", "berthoud"]),
    ("Festina", &["festina"]),
    ("Fendi", &["fendi"]),
    ("Flik Flak", &["flik", "flak"]),
    ("Fiona Krüger", &["fiona", "kruger"]),
    ("Fortis", &["fortis"]),
    ("Franck Muller", &["franck", "muller"]),
    ("Frédéric Jouvenot", &["frederic", "jouvenot"]),
    ("Scuderia Ferrari", &["scuderia", "ferrari"]),
    ("Frédérique Constant", &["frederique", "constant"]),
    ("Gallet & Co", &["gallet", "co"]),
    ("Girard-Perregaux", &["girard-perregaux"]),
    ("Glashütte Original", &["glashutte", "original"]),
    ("George Daniels", &["george", "daniels"]),
    ("Gorilla", &["gorilla"]),
    ("Georg Jensen", &["georg", "jensen"]),
    ("Graff", &["graff"]),
    ("Garmin", &["garmin"]),
    ("Graham", &["graham"]),
    ("Glycine", &["glycine"]),
    ("Greubel Forsey", &["greubel", "forsey"]),
    ("Grönefeld", &["gronefeld"]),
    ("Gucci", &["gucci"]),
    ("Grand Seiko", &["grand", "seiko"]),
    ("Guess", &["guess"]),
    ("Halda Watch Co", &["halda", "watch", "co"]),
    ("H. Moser & Cie", &["h.", "moser", "cie"]),
    ("Hamilton", &["hamilton"]),
    ("Hanhart", &["hanhart"]),
    ("Harry Winston", &["harry", "winston"]),
    ("Hautlence", &["hautlence"]),
    ("Hegid", &["hegid"]),
    ("Hermès", &["hermes"]),
    ("Henry London", &["henry", "london"]),
    ("Hublot", &["hublot"]),
    ("Hysek", &["hysek"]),
    ("HYT", &["hyt"]),
    ("Ikepod", &["ikepod"]),
    ("Ingersoll", &["ingersoll"]),
    ("Itay Noy", &["itay", "noy"]),
    ("Invicta", &["invicta"]),
    ("IWC", &["iwc"]),
    ("Jacob & Co", &["jacob", "co"]),
    ("Jaipur Watch Company", &["jaipur", "watch", "company"]),
    ("Jaeger-LeCoultre", &["jaeger-lecoultre"]),
    ("Jaquet Droz", &["jaquet", "droz"]),
    ("Junghans", &["junghans"]),
    ("Krayon", &["krayon"]),
    ("Kronaby", &["kronaby"]),
    ("Kienzle", &["kienzle"]),
    ("Konstantin Chaykin", &["konstantin", "chaykin"]),
    ("Laurent Ferrier", &["laurent", "ferrier"]),
    ("Lancashire Watch Company", &["lancashire", "watch", "company"]),
    ("Larsson & Jennings", &["larsson", "jennings"]),
    ("Lang & Heyne", &["lang", "heyne"]),
    ("Lacoste", &["lacoste"]),
    ("Laco Uhrenmanufaktur", &["laco", "uhrenmanufaktur"]),
    ("Linde Werdelin", &["linde", "werdelin"]),
    ("Lip", &["lip"]),
    ("Leijona watch", &["leijona", "watch"]),
    ("Lemania", &["lemania"]),
    ("Longines", &["longines"]),
    ("Lilienthal Berlin", &["lilienthal", "berlin"]),
    ("Louis Erard", &["louis", "erard"]),
    ("Locman", &["locman"]),
    ("Louis Moinet", &["louis", "moinet"]),
    ("Lorus", &["lorus"]),
    ("Louis Vuitton", &["louis", "vuitton"]),
    ("Ludovic Ballouard", &["ludovic", "ballouard"]),
    ("Luminox", &["luminox"]),
    ("Lundis Bleus", &["lundis", "bleus"]),
    ("Lytt Labs", &["lytt", "labs"]),
    ("Manufacture Royale", &["manufacture", "royale"]),
    ("Maurice de Mauriac", &["maurice", "de", "mauriac"]),
    ("Maitres du Temps", &["maitres", "du", "temps"]),
    ("Manhattan Watch Company", &["manhattan", "watch", "company"]),
    ("Maurice Lacroix", &["maurice", "lacroix"]),
    ("MB&F", &["mb&f"]),
    ("Meccaniche Veloci", &["meccaniche", "veloci"]),
    ("Michel Herbelin", &["michel", "herbelin"]),
    ("Moschino", &["moschino"]),
    ("Michael Kors", &["michael", "kors"]),
    ("MeisterSinger", &["meistersinger"]),
    ("Mondaine", &["mondaine"]),
    ("Montblanc", &["montblanc"]),
    ("Moritz Grossmann", &["moritz", "grossmann"]),
    ("MVMT", &["mvmt"]),
    ("Movado", &["movado"]),
    ("MW&Co", &["mw&co"]),
    ("Nomos Glashütte", &["nomos", "glashutte"]),
    ("Newgate Watches", &["newgate", "watches"]),
    ("Nivada", &["nivada"]),
    ("Nixon", &["nixon"]),
    ("Omega", &["omega"]),
    ("Olivia Burton", &["olivia", "burton"]),
    ("ORIENT", &["orient"]),
    ("ORIENT STAR", &["orient", "star"]),
    ("Oris", &["oris"]),
    ("Panerai", &["panerai"]),
    ("Parmigiani Fleurier", &["parmigiani", "fleurier"]),
    ("Patek Philippe", &["patek", "philippe"]),
    ("Perrelet", &["perrelet"]),
    ("Pequignet", &["pequignet"]),
    ("Philipp Plein", &["philipp", "plein"]),
    ("Pulsar", &["pulsar"]),
    ("Prada", &["prada"]),
    ("Police", &["police"]),
    ("Piaget", &["piaget"]),
    ("Purnell", &["purnell"]),
    ("Rado", &["rado"]),
    ("Raketa", &["raketa"]),
    ("Ralph Lauren", &["ralph", "lauren"]),
    ("Raymond Weil", &["raymond", "weil"]),
    ("Rebellion", &["rebellion"]),
    ("Ressence", &["ressence"]),
    ("Roger W. Smith", &["roger", "w.", "smith"]),
    ("Richard Mille", &["richard", "mille"]),
    ("Riskers", &["riskers"]),
    ("Roger Dubuis", &["roger", "dubuis"]),
    ("Rolex", &["rolex"]),
    ("Rotary", &["rotary"]),
    ("Romain Gauthier", &["romain", "gauthier"]),
    ("Sarpaneva", &["sarpaneva"]),
    ("Schwarz Etienne", &["schwarz", "etienne"]),
    ("Seiko", &["seiko"]),
    ("Skagen", &["skagen"]),
    ("Sjöö Sandström", &["sjoo", "sandstrom"]),
    ("SevenFriday", &["sevenfriday"]),
    ("Slow watch", &["slow", "watch"]),
    ("Shinola", &["shinola"]),
    ("Swiss Military Hanowa", &["swiss", "military", "hanowa"]),
    ("Stührling", &["stuhrling"]),
    ("Stowa", &["stowa"]),
    ("Singer Reimagined", &["singer", "reimagined"]),
    ("Sinn", &["sinn"]),
    ("Suunto", &["suunto"]),
    ("Superdry", &["superdry"]),
    ("Sekonda", &["sekonda"]),
    ("Speake-Marin", &["speake-marin"]),
    ("Swarovski", &["swarovski"]),
    ("Spinnaker", &["spinnaker"]),
    ("Swatch", &["swatch"]),
    ("TAG Heuer", &["tag", "heuer"]),
    ("Heuer", &["heuer"]),
    ("Ted Baker", &["ted", "baker"]),
    ("Tiffany & Co.", &["tiffany", "c"]),
    ("Tissot", &["tissot"]),
    ("Timex", &["timex"]),
    ("ToyWatch", &["toywatch"]),
    ("Titoni", &["titoni"]),
    ("Tommy Hilfiger", &["tommy", "hilfiger"]),
    ("Tockr", &["tockr"]),
    ("TUDOR", &["tudor"]),
    ("Tutima Glashütte", &["tutima", "glashutte"]),
    ("Timberland", &["timberland"]),
    ("TW Steel", &["tw", "steel"]),
    ("U-Boat", &["u-boat"]),
    ("Ulysse Nardin", &["ulysse", "nardin"]),
    ("Urwerk", &["urwerk"]),
    ("Universal Geneve", &["universal", "geneve"]),
    ("Vacheron Constantin", &["vacheron", "constantin"]),
    ("Van Cleef & Arpels", &["van", "cleef", "arpels"]),
    ("Versace", &["versace"]),
    ("Victorinox", &["victorinox"]),
    ("Voutilainen", &["voutilainen"]),
    ("Vulcain", &["vulcain"]),
    ("Venezianico", &["venezianico"]),
    ("Vostok", &["vostok"]),
    ("Wittnauer", &["wittnauer"]),
    ("Yema", &["yema"]),
    ("Zeitwinkel", &["zeitwinkel"]),
    ("Zeppelin", &["zeppelin"]),
    ("Zenith", &["zenith"]),
    ("Zodiac", &["zodiac"]),
];