pub const BRANDS: &[&str] = &[
    "A. Favre & Fils",
    "Adidas Originals",
    "Arnold & Son",
    "A. Lange & Söhne",
    "Accurist",
    "Abraham-Louis Breguet",
    "Adriatica",
    "ADINA Watches",
    "Anne Klein",
    "A.L.B Atelier Le Brézéguet",
    "Amanda Walker",
    "Alba",
    "Alexandre Christie",
    "Andreas Osten",
    "Andersen Geneve",
    "Ansonia Clock Company",
    "American Waltham Watch Company",
    "Armani Exchange",
    "Apple",
    "anOrdain",
    "August Berg x Morris & Co",
    "AKRIVIA",
    "Akrone",
    "AVI-8",
    "Alexander Shorokhoff",
    "Alpina",
    "Aragon",
    "Andreas Strehler",
    "Angelus",
    "Anonimo",
    "Antoine Preziuso",
    "Armand Nicolet",
    "Armin Strom",
    "Armitron",
    "Ateliers de Monaco",
    "Audemars Piguet",
    "Auguste Reymond",
    "Azimuth",
    "Aquastar",
    "Backes & Strauss",
    "Ball Watch",
    "Bausele",
    "Bruno Sohnle",
    "B-UHR",
    "Baume & Mercier",
    "Bell & Ross",
    "Bovet Fleurier",
    "Bedat & Co",
    "Benrus",
    "Blancpain",
    "Blumarine",
    "Ben Sherman",
    "Bulova",
    "Breil",
    "Bomberg",
    "Bovet",
    "Breguet",
    "Breitling",
    "Brellum",
    "Bremont",
    "Bvlgari",
    "Burberry",
    "Buccellati",
    "Carl F. Bucherer",
    "Carl Suchy & Söhne",
    "Cartier",
    "Calvin Klein",
    "Catorex",
    "Carlo Ferrara",
    "Century",
    "Certina",
    "Cecil Purnell",
    "Christian Jacques",
    "Christopher Ward",
    "Chanel",
    "Charriol",
    "Chopard",
    "Citizen",
    "Coach",
    "Christophe Claret",
    "Chronoswiss",
    "Charles Jourdan",
    "Calypso",
    "Claude Meylan",
    "Charlotte Raffaelli",
    "Cluse",
    "Code41",
    "Corum",
    "CT Scuderia",
    "Cuervo y Sobrinos",
    "Cvstos",
    "Cyrus",
    "Czapek",
    "Daniel Wellington",
    "De Bethune",
    "Dewitt",
    "DKNY",
    "Dakota Watch Company",
    "Dior",
    "Damasko",
    "D. Dornblüth & Sohn",
    "Damiani",
    "Dan henry",
    "D1 Milano",
    "Depth Charge",
    "Delbana",
    "Diesel",
    "Delma",
    "Dietrich",
    "Dreffa",
    "Dubey Schaldenbrand",
    "Doxa",
    "Ebel",
    "Eberhard & Co",
    "Edox",
    "EHF Horlogere",
    "EPOS",
    "Ernest Borel",
    "Emile Chouriet",
    "Eterna",
    "Elliot Brown",
    "Epoch Stockholm",
    "EverSwiss",
    "F. P. Journe",
    "Fabergé",
    "Favre Leuba",
    "Ferdinand Berthoud",
    "Festina",
    "Fendi",
    "Flik Flak",
    "Fiona Krüger",
    "Fortis",
    "Franck Muller",
    "Frédéric Jouvenot",
    "Scuderia Ferrari",
    "Frédérique Constant",
    "Gallet & Co",
    "Girard-Perregaux",
    "Glashütte Original",
    "George Daniels",
    "Gorilla",
    "Georg Jensen",
    "Graff",
    "Garmin",
    "Graham",
    "Glycine",
    "Greubel Forsey",
    "Grönefeld",
    "Gucci",
    "Grand Seiko",
    "Guess",
    "Halda Watch Co",
    "H. Moser & Cie",
    "Hamilton",
    "Hanhart",
    "Harry Winston",
    "Hautlence",
    "Hegid",
    "Hermès",
    "Henry London",
    "Hublot",
    "Hysek",
    "HYT",
    "Ikepod",
    "Ingersoll",
    "Itay Noy",
    "Invicta",
    "IWC",
    "Jacob & Co",
    "Jaipur Watch Company",
    "Jaeger-LeCoultre",
    "Jaquet Droz",
    "Junghans",
    "Krayon",
    "Kronaby",
    "Kienzle",
    "Konstantin Chaykin",
    "Laurent Ferrier",
    "Lancashire Watch Company",
    "Larsson & Jennings",
    "Lang & Heyne",
    "Lacoste",
    "Laco Uhrenmanufaktur",
    "Linde Werdelin",
    "Lip",
    "Leijona watch",
    "Lemania",
    "Longines",
    "Lilienthal Berlin",
    "Louis Erard",
    "Locman",
    "Louis Moinet",
    "Lorus",
    "Louis Vuitton",
    "Ludovic Ballouard",
    "Luminox",
    "Lundis Bleus",
    "Lytt Labs",
    "Manufacture Royale",
    "Maurice de Mauriac",
    "Maitres du Temps",
    "Manhattan Watch Company",
    "Maurice Lacroix",
    "MB&F",
    "Meccaniche Veloci",
    "Michel Herbelin",
    "Moschino",
    "Michael Kors",
    "MeisterSinger",
    "Mondaine",
    "Montblanc",
    "Moritz Grossmann",
    "MVMT",
    "Movado",
    "MW&Co",
    "Nomos Glashütte",
    "Newgate Watches",
    "Nivada",
    "Nixon",
    "Omega",
    "Olivia Burton",
    "ORIENT",
    "ORIENT STAR",
    "Oris",
    "Panerai",
    "Parmigiani Fleurier",
    "Patek Philippe",
    "Perrelet",
    "Pequignet",
    "Philipp Plein",
    "Pulsar",
    "Prada",
    "Police",
    "Piaget",
    "Purnell",
    "Rado",
    "Raketa",
    "Ralph Lauren",
    "Raymond Weil",
    "Rebellion",
    "Ressence",
    "Roger W. Smith",
    "Richard Mille",
    "Riskers",
    "Roger Dubuis",
    "Rolex",
    "Rotary",
    "Romain Gauthier",
    "Sarpaneva",
    "Schwarz Etienne",
    "Seiko",
    "Skagen",
    "Sjöö Sandström",
    "SevenFriday",
    "Slow watch",
    "Shinola",
    "Swiss Military Hanowa",
    "Stührling",
    "Stowa",
    "Singer Reimagined",
    "Sinn",
    "Suunto",
    "Superdry",
    "Sekonda",
    "Speake-Marin",
    "Swarovski",
    "Spinnaker",
    "Swatch",
    "TAG Heuer",
    "Heuer",
    "Ted Baker",
    "Tiffany & Co.",
    "Tissot",
    "Timex",
    "ToyWatch",
    "Titoni",
    "Tommy Hilfiger",
    "Tockr",
    "TUDOR",
    "Tutima Glashütte",
    "Timberland",
    "TW Steel",
    "U-Boat",
    "Ulysse Nardin",
    "Urwerk",
    "Universal Geneve",
    "Vacheron Constantin",
    "Van Cleef & Arpels",
    "Versace",
    "Victorinox",
    "Voutilainen",
    "Vulcain",
    "Venezianico",
    "Vostok",
    "Wittnauer",
    "Yema",
    "Zeitwinkel",
    "Zeppelin",
    "Zenith",
    "Zodiac",
];
